### PR TITLE
Update to the new Apple WWDR intermediate certificate

### PR DESCRIPTION
**Pull request by ghost**
If a new certificate is generated after January 28, 2021 and the old intermediate is used in the certificate chain, apps will crash on launch in jailed state.

https://developer.apple.com/support/wwdr-intermediate-certificate/

I don't have a device to test this on right now but the fix seems pretty straightforward, see https://github.com/rileytestut/AltSign/commit/8ce86befc8621c290ef916f8694a0ffc3cd99f14.

~~Also, people who are still using an older certificate will have to revoke it and resign apps with a new certificate after installing this update, otherwise their apps will crash after they're resigned.~~ I've added more code to make sure both old and new certs will work, but it still requires testing.

### CODE REVIEW

**Comment by Matchstic** [comment]
Hey, thanks for making this change!

To be honest, I’m on the fence about accepting this. Whilst this will very likely fix the issue in question, I *really* don’t want the general jailbreak community thinking this project is still active. This is because I’ll be again inundated with requests to update it, and I just don’t want deal with that, or the project in general. Even though I would be clearly stating this is your change, not many people actually read the changelog... 😔

Thoughts?

**Comment by ghost** [comment]
Yeah, good point, I'm not sure. A few people still use ReProvision after installing a jailbreak from a signing service because installing AltStore/AltDaemon without using a computer for the initial setup is not officially supported, but there are workarounds.

**Comment by ghost** [comment]
Though if you choose not to merge the PR, people may be left under the impression that ReProvision still works, because it will still *appear* to sign apps correctly and they will open in jailbroken state, but they will crash when opening them in jailed state.

**Comment by Matchstic** [comment]
Hmm.

Going from gut instinct on this, I think I’m not going to accept + publish this change. If you want to build and release it, that’s fine. If you decide to do that, please make sure to update the contact information in the control file, and grey out the link to my Twitter in the settings page.

I’ll be making an announcement on Twitter stating that ReProvision is completely broken now, where apps appear signed but no longer are.

**Pull request closed without merging**
