### PR TITLE
Switched to new Apple API

### PR DESCRIPTION
**Pull request by TrungNguyen1909**
Addressed #96 
Cleaned up EEAppleServices.m

I used AuthKit to handle the headers and authentication stuffs.
I used AuthKitUI to create the login screen. 

**EDIT**: URGH, Actually, There's a way to login with the real username and password. What do you guys prefer? AuthKit supports login programmatically with username & password.

AuthKit needs a special entitlements called `com.apple.authkit.client.private`. On jailbroken iOS, we can sign entitlements arbitrarily, but on macOS, you will need to turn off SIP and get rid of amfid(which is not so good). Maybe someone will reverse the AuthKit and handle them locally. (Wait, how about patching the `akd` and run it on our own so we don't need the special entitlements?). But to sign on Windows, we definitely need to replicate `akd` with our owned code.

As a result, there're a few things left to be done:
- Error handling. I'm not really sure if all errors have been handled correctly. Time will tell.

- UI code, some views are now redundant and should be removed. I left some throw there in case that weird errors caused by authentication. There're some pieces of code that have been commented out(or not) followed the throw statements.

### CODE REVIEW

**Comment by Matchstic** [comment]
Programmatic login is much more preferred if possible please!

**Comment by TrungNguyen1909** [comment]
@Matchstic, the token you received are meant to be saved for a long time.

**Comment by Matchstic** [comment]
Perfect, thanks. I've just observed the same myself about the token; had assumed it was in this PR. I've moved everything over to silent auth now and dropped the AuthKitUI dependency, caching the AltDSIS in the format you did, alongside the GS token. Works well from what I can see!

**Review by Ellitvin115 — COMMENTED** [review]
#170

**Pull request merged**
